In [1]:
import numpy as np
import pandas as pd

Wine = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv', sep=';')

print(Wine.columns)
print(Wine.shape)

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')
(4898, 12)


In [2]:
Wine.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [4]:
from sklearn import metrics
from sklearn.model_selection import train_test_split

x= Wine.iloc[:,:-1]
y=Wine.iloc[:,11]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20)

# KNN

In [7]:
from sklearn.neighbors import KNeighborsClassifier
#Create KNN Classifier
knn = KNeighborsClassifier(n_neighbors=3)
# Train the model using the training sets
knn.fit(X_train, y_train)
#predict the response for test dataset

y_pred = knn.predict(X_test)

#Model accuracy, how often is the classifier correct ?
print('Accuracy : ', metrics.accuracy_score(y_test, y_pred))

from sklearn.metrics import classification_report, confusion_matrix
print('====Confusion Matrix ====')
print(confusion_matrix(y_test, y_pred))

print('====Classification Report ====')
print(classification_report(y_test, y_pred))


Accuracy :  0.48775510204081635
====Confusion Matrix ====
[[  0   2   2   2   0   0   0]
 [  1   7  12  11   6   0   0]
 [  2  15 154 110  13   1   0]
 [  1  13 124 249  50   6   0]
 [  1   1  39  65  65   0   0]
 [  0   0   8  15   1   3   0]
 [  0   0   0   1   0   0   0]]
====Classification Report ====
             precision    recall  f1-score   support

          3       0.00      0.00      0.00         6
          4       0.18      0.19      0.19        37
          5       0.45      0.52      0.49       295
          6       0.55      0.56      0.56       443
          7       0.48      0.38      0.42       171
          8       0.30      0.11      0.16        27
          9       0.00      0.00      0.00         1

avg / total       0.48      0.49      0.48       980



C:\Users\Veena\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [8]:
new_observation = [6.7,0.15,0.38,1.7,0.037,20,84,0.99046,3.09,0.53,11.4]

y_pred = knn.predict([new_observation])

probability = knn.predict_proba([new_observation])

print('Predicted wine quality value is :', y_pred)

print('Predicted probability is : ', probability)

Predicted wine quality value is : [4]
Predicted probability is :  [[0.         0.33333333 0.33333333 0.33333333 0.         0.
  0.        ]]


# Multi Class Logistic Regression

In [12]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(random_state=0, multi_class='multinomial', solver='newton-cg')
# Train model
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)

print('Accuracy thru Multiclass Logistic Regression ', metrics.accuracy_score(y_test, y_pred))

Accuracy thru Multiclass Logistic Regression  0.5244897959183673


# Ordinal Logistic Regression

In [13]:
olr = LogisticRegression(solver = 'lbfgs')
olr.fit(X_train, y_train)

y_pred = olr.predict(X_test)
print('Accuracy thru Ordinal Logistic Regression ', metrics.accuracy_score(y_test, y_pred))


Accuracy thru Ordinal Logistic Regression  0.5275510204081633


# Naive Bayes

In [19]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB

#create a Gaussian classifier
gnb = GaussianNB()

gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)
print('Accuracy thru Gaussian Naive Bayes ', metrics.accuracy_score(y_test, y_pred))

Accuracy thru Gaussian Naive Bayes  0.4387755102040816


In [20]:
mnb = MultinomialNB()

mnb.fit(X_train, y_train)
y_pred = mnb.predict(X_test)
print('Accuracy thru Multi nomial Naive Bayes ', metrics.accuracy_score(y_test, y_pred))

Accuracy thru Multi nomial Naive Bayes  0.3816326530612245


In [21]:
from sklearn.naive_bayes import BernoulliNB

bnb = BernoulliNB()

bnb.fit(X_train, y_train)
y_pred = bnb.predict(X_test)
print('Accuracy thru Bernoulli Naive Bayes ', metrics.accuracy_score(y_test, y_pred))

Accuracy thru Bernoulli Naive Bayes  0.4520408163265306
