In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [3]:
data=pd.read_csv("D:\\datasets\\glass.csv")
data.head()

RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [5]:
data.shape

(214, 10)

In [7]:
cor=data.corr()
 

RI        Na        Mg        Al        Si         K        Ca  \
RI    1.000000 -0.191885 -0.122274 -0.407326 -0.542052 -0.289833  0.810403   
Na   -0.191885  1.000000 -0.273732  0.156794 -0.069809 -0.266087 -0.275442   
Mg   -0.122274 -0.273732  1.000000 -0.481799 -0.165927  0.005396 -0.443750   
Al   -0.407326  0.156794 -0.481799  1.000000 -0.005524  0.325958 -0.259592   
Si   -0.542052 -0.069809 -0.165927 -0.005524  1.000000 -0.193331 -0.208732   
K    -0.289833 -0.266087  0.005396  0.325958 -0.193331  1.000000 -0.317836   
Ca    0.810403 -0.275442 -0.443750 -0.259592 -0.208732 -0.317836  1.000000   
Ba   -0.000386  0.326603 -0.492262  0.479404 -0.102151 -0.042618 -0.112841   
Fe    0.143010 -0.241346  0.083060 -0.074402 -0.094201 -0.007719  0.124968   
Type -0.164237  0.502898 -0.744993  0.598829  0.151565 -0.010054  0.000952   

            Ba        Fe      Type  
RI   -0.000386  0.143010 -0.164237  
Na    0.326603 -0.241346  0.502898  
Mg   -0.492262  0.083060 -0.744993  
Al    0.479404 -0.074402  0.598829  
Si   -0.102151 -0.094201  0.151565  
K    -0.042618 -0.007719 -0.010054  
Ca   -0.112841  0.124968  0.000952  
Ba    1.000000 -0.058692  0.575161  
Fe   -0.058692  1.000000 -0.188278  
Type  0.575161 -0.188278  1.000000

In [44]:
cor.style.background_gradient(cmap='coolwarm')

In [16]:
X=data.iloc[:,0:9]
y=data.iloc[:,-1]

In [32]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =train_test_split(X,y, test_size =0.2,random_state =1)

In [33]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression(multi_class='multinomial', random_state=0,solver='newton-cg')
logreg.fit(X_train, y_train)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='multinomial', n_jobs=None, penalty='l2',
                   random_state=0, solver='newton-cg', tol=0.0001, verbose=0,
                   warm_start=False)

In [34]:
y_pred = logreg.predict(X_test)

In [35]:
from sklearn import metrics
cnf_mat=metrics.confusion_matrix(y_test,y_pred)
print(cnf_mat)
print('Accuracy',metrics.accuracy_score(y_test,y_pred))



[[13  6  0  0  0  0]
 [ 1  8  0  2  1  0]
 [ 3  3  0  0  0  0]
 [ 0  0  0  1  0  0]
 [ 0  0  0  0  1  0]
 [ 0  0  0  0  0  4]]
Accuracy 0.627906976744186


In [36]:
y_pred

array([6, 7, 5, 5, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 2, 2, 1, 1, 1, 2, 7,
       2, 1, 2, 1, 2, 2, 2, 1, 5, 6, 2, 1, 2, 1, 2, 2, 2, 2, 1, 7, 7],
      dtype=int64)

In [42]:
#New data
new=[1.343,5.657,3.56,0,0,0,1.5,2.5,0]
y_pred=logreg.predict([new])
y_pred


array([5], dtype=int64)

In [43]:
probability=logreg.predict_proba([new])
probability

array([[1.89558995e-43, 1.07854712e-10, 8.11299856e-12, 1.00000000e+00,
        8.00991465e-51, 2.30965339e-25]])